version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # default RabbitMQ port
      - "15672:15672"   # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks: 
      - ecommerce-network

  postgres_user:
    image: postgres
    container_name: postgres_user
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5443:5432"
    networks: 
      - ecommerce-network

  postgres_product:
    image: postgres
    container_name: postgres_product
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: product
      POSTGRES_PASSWORD: password
    ports:
      - "5444:5432"
    networks: 
      - ecommerce-network

  postgres_order:
    image: postgres
    container_name: postgres_order
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: order
      POSTGRES_PASSWORD: password
    ports:
      - "5445:5432"
    networks: 
      - ecommerce-network

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "5031:80"
    depends_on:
      - postgres_user
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: 
      - ecommerce-network

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    ports:
      - "5032:80"
    depends_on:
      - postgres_product
      - rabbitmq
    networks: 
      - ecommerce-network

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    ports:
      - "5033:80"
    depends_on:
      - postgres_order
      - rabbitmq
    networks: 
      - ecommerce-network
  
  ecommerce-frontend:
    build:
      context: .
      dockerfile: ecommerce-frontend/DockerFile
    ports:
      - "5000:80"
    depends_on:
      - user-service
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge


  
